### ISSUE TITLE
Deprecated data types should be converted ( SQL Server NTEXT, TEXT, IMAGE )

### ISSUE THREAD

**Issue by axelgr74** [SAP/sap-commerce-db-sync#19]
See https://learn.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2016?view=sql-server-ver16#features-deprecated-in-a-future-version-of-sql-server

There's a range of deprecated SQL Server data types (NTEXT, TEXT, IMAGE) which existing Commerce databases may still use, simply because Commerce did use them in historical versions and Commerce does never change column types. These columns will not work optimally in SQL Azure today (e.g. index optimisation cannot be done online) and should be changed ( e.g. to NVARCHAR(MAX), NVARRBINARY(MAX) ).

Database migration is a one-moment-in-time opportunity to perform that step without the otherwise inevitable need to perform a table modification with downtime.

**Comment by lnowakowski** [comment]
Can you please provide some more hybris/Commerce version specific examples? From what I recall (I checked only up to 5.7) for MSSQL `IMAGE` type was used to store _java.io.Serializable_ up to version 6.7, after that it was changed to `VARBINARY(MAX)`, other types of "unclassified text data" (_HYBRIS.LONG_STRING_ etc.) was persisted as `NVARCHAR(MAX)`
