### ISSUE TITLE
Access to quick demo video

### ISSUE THREAD

**Issue by vvillalo** [SAP/sap-commerce-db-sync#21]
Would be possible to have access to the video posted in https://github.com/SAP/sap-commerce-db-sync?tab=readme-ov-file#quick-demo

https://video.sap.com/embed/secure/iframe/entryId/1_7bhihtlz/uiConfId/30317401/st/0

Thanks in advance!

**Comment by YannickRobin** [comment]
Hello, can you please try the following link and confirm: https://sapvideo.cfapps.eu10-004.hana.ondemand.com/?entry_id=1_7bhihtlz .

Thanks,

Yannick

**Comment by vvillalo** [comment]
I can see it now thanks.
