### ISSUE TITLE
AzureCloudUtils Missing method hasValidMediaFolderName

### ISSUE THREAD

**Issue by HSorensen** [SAP/sap-commerce-db-sync#4]
Does anyone have a solution for this error:

Missing boolean de.hybris.platform.azure.media.AzureCloudUtils.hasValidMediaFolderName (de.hybris.platform.media.storage.MediaStorageConfigService$MediaFolderConfig)'

Looking at [AzureCloudUtils.java](https://github.com/SAP/sap-commerce-db-sync/blob/main/commercedbsync/src/de/hybris/platform/azure/media/AzureCloudUtils.java)

The method clearly isn't there.

Any ideas ?

**Comment by ashwinineha** [comment]
@HSorensen , thank you for reporting it, we have applied the [patch](https://github.com/SAP/sap-commerce-db-sync/commit/8855b00e849ad58c1b83bb763a0aaa1cb5832a17)  . Let us know if you are still facing the issue. 

Regards,

**Comment by HSorensen** [comment]
@ashwinineha Will you be creating a new release with this fix ?

**Comment by ashwinineha** [comment]
@HSorensen  , Please pull the latest code from repo. 

Thanks,

**Comment by ashwinineha** [comment]
Fixed !

**Comment by ashwinineha** [comment]
Fixed!
